
CREATE TABLE public.invite_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  is_used boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  used_by uuid,
  used_at timestamp with time zone,
  created_by uuid,
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  invite_type text CHECK (invite_type IS NULL OR (invite_type = ANY (ARRAY['vip_30_days'::text, 'vip_lifetime'::text, 'vip_custom'::text]))),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT invite_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.market_drivers (
  id bigint NOT NULL,
  nome text,
  nacionalidade text,
  total integer,
  concentracao integer,
  talento integer,
  agressividade integer,
  experiencia integer,
  tecnica integer,
  resistencia integer,
  carisma integer,
  motivacao integer,
  reputacao integer,
  peso integer,
  idade integer,
  salario integer,
  taxa integer,
  ofertas integer,
  nivel integer,
  favorito text,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  aposentadoria text,
  CONSTRAINT market_drivers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.calendario_temporada (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  season_num text,
  start_date text,
  end_date text,
  tracks_json jsonb,
  test_track text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendario_temporada_pkey PRIMARY KEY (id),
  CONSTRAINT calendario_temporada_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_planning (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_planning_pkey PRIMARY KEY (id),
  CONSTRAINT user_planning_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.energy_observations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  track_name text NOT NULL,
  track_factor numeric NOT NULL,
  energia_inicial numeric NOT NULL CHECK (energia_inicial >= 0::numeric AND energia_inicial <= 100::numeric),
  energia_final numeric NOT NULL CHECK (energia_final >= 0::numeric AND energia_final <= 100::numeric),
  perda_energia numeric NOT NULL,
  xp integer NOT NULL CHECK (xp IS NULL OR xp >= 0 AND xp <= 300),
  stamina integer NOT NULL CHECK (stamina IS NULL OR stamina >= 0 AND stamina <= 250),
  idade integer NOT NULL CHECK (idade IS NULL OR idade >= 0 AND idade <= 50),
  peso integer NOT NULL CHECK (peso IS NULL OR peso >= 0 AND peso <= 100),
  ctr integer NOT NULL CHECK (ctr IS NULL OR ctr >= 0 AND ctr <= 100),
  user_id uuid,
  chassis integer CHECK (chassis IS NULL OR chassis >= 0 AND chassis <= 9),
  engine integer CHECK (engine IS NULL OR engine >= 0 AND engine <= 9),
  front_wing integer CHECK (front_wing IS NULL OR front_wing >= 0 AND front_wing <= 9),
  rear_wing integer CHECK (rear_wing IS NULL OR rear_wing >= 0 AND rear_wing <= 9),
  underbody integer CHECK (underbody IS NULL OR underbody >= 0 AND underbody <= 9),
  sidepods integer CHECK (sidepods IS NULL OR sidepods >= 0 AND sidepods <= 9),
  cooling integer CHECK (cooling IS NULL OR cooling >= 0 AND cooling <= 9),
  gearbox integer CHECK (gearbox IS NULL OR gearbox >= 0 AND gearbox <= 9),
  brakes integer CHECK (brakes IS NULL OR brakes >= 0 AND brakes <= 9),
  suspension integer CHECK (suspension IS NULL OR suspension >= 0 AND suspension <= 9),
  electronics integer CHECK (electronics IS NULL OR electronics >= 0 AND electronics <= 9),
  race_completed boolean DEFAULT false,
  source character varying,
  race_clean boolean DEFAULT false,
  weather character varying DEFAULT 'Seca'::character varying,
  final_position integer,
  reliability integer DEFAULT 5 CHECK (reliability >= 1 AND reliability <= 5),
  temporada character varying,
  corrida character varying,
  voltas integer,
  corners integer,
  weather_condition character varying DEFAULT 'SECA'::character varying CHECK (weather_condition::text = ANY (ARRAY['SECA'::character varying, 'MOLHADA'::character varying, 'MISTA'::character varying]::text[])),
  validation_status character varying DEFAULT 'VALIDA'::character varying CHECK (validation_status::text = ANY (ARRAY['VALIDA'::character varying, 'SUSPEITA'::character varying, 'DESCARTADA'::character varying]::text[])),
  observacoes text,
  CONSTRAINT energy_observations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gpro_sponsors (
  sponsor_id bigint NOT NULL,
  name text NOT NULL,
  country text,
  category text,
  finances integer,
  expectations integer,
  patience integer,
  reputation integer,
  image integer,
  negotiation integer,
  raw_data jsonb NOT NULL,
  last_sync_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gpro_sponsors_pkey PRIMARY KEY (sponsor_id)
);
CREATE TABLE public.gpro_sponsors_metadata (
  key text NOT NULL,
  value jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gpro_sponsors_metadata_pkey PRIMARY KEY (key)
);
CREATE TABLE public.api_knowledge_base (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  campos jsonb NOT NULL DEFAULT '[]'::jsonb,
  tipos jsonb NOT NULL DEFAULT '{}'::jsonb,
  parametros jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_campos integer DEFAULT 0,
  status text DEFAULT '🔍 Pendente'::text,
  maturidade text DEFAULT 'descoberto'::text,
  confianca integer DEFAULT 10,
  ultimo_hash text,
  historico jsonb DEFAULT '[]'::jsonb,
  observacoes text,
  utilidade integer DEFAULT 3,
  scans_realizados integer DEFAULT 0,
  ultimo_scan timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  hash_history jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT api_knowledge_base_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gpro_import_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  season integer,
  race integer,
  payload jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gpro_import_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_state (
  user_id uuid NOT NULL,
  role text DEFAULT 'user'::text,
  track text DEFAULT 'Selecionar Pista'::text,
  driver_json jsonb DEFAULT '{}'::jsonb,
  car_json jsonb DEFAULT '[]'::jsonb,
  tech_director_json jsonb DEFAULT '{}'::jsonb,
  staff_facilities_json jsonb DEFAULT '{}'::jsonb,
  test_points_json jsonb DEFAULT '{"accel": 0, "power": 0, "handling": 0}'::jsonb,
  race_options_json jsonb DEFAULT '{}'::jsonb,
  weather_data jsonb DEFAULT '{}'::jsonb,
  sponsors_database_json jsonb DEFAULT '[]'::jsonb,
  energy_coeffs_json jsonb DEFAULT '{}'::jsonb,
  menu_data jsonb DEFAULT '{}'::jsonb,
  office_data jsonb DEFAULT '{}'::jsonb,
  desgaste_modifier numeric DEFAULT 0,
  gpro_token text,
  last_import_snapshot jsonb DEFAULT '{}'::jsonb,
  last_import_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  car_development_json jsonb DEFAULT '{}'::jsonb,
  driver_info jsonb,
  driver_editable jsonb,
  driver_static jsonb,
  car_totals jsonb,
  car_characteristic jsonb,
  vip_status text,
  vip_expires_at timestamp with time zone,
  access_plan text,
  access_grant_id uuid,
  CONSTRAINT user_state_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.access_grants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  source text NOT NULL CHECK (source = ANY (ARRAY['invite'::text, 'manual'::text, 'payment'::text, 'admin'::text])),
  invite_code_id uuid,
  plan text NOT NULL CHECK (plan = ANY (ARRAY['premium'::text, 'full_premium'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'revoked'::text, 'pending'::text])),
  starts_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT access_grants_pkey PRIMARY KEY (id),
  CONSTRAINT access_grants_invite_code_id_fkey FOREIGN KEY (invite_code_id) REFERENCES public.invite_codes(id)
);
CREATE TABLE public.access_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  access_grant_id uuid,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['granted'::text, 'renewed'::text, 'revoked'::text, 'expired'::text, 'manually_adjusted'::text])),
  source text,
  actor_user_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT access_events_pkey PRIMARY KEY (id),
  CONSTRAINT access_events_access_grant_id_fkey FOREIGN KEY (access_grant_id) REFERENCES public.access_grants(id)
);